### PR TITLE
Edit css-one-liners.md

### PR DESCRIPTION
**Pull request by Sparsh47**
Type of Change
Adding a new entry

Checklist
- [x] All writings are my own.
- [x]  My changes generate no new warnings.
- [x]  I have performed a self-review of my own writing and code.
- [x]  I have checked my entry and corrected any misspellings.
- [x]  I have made corresponding changes to the documentation if needed.

### CODE REVIEW

**Comment by jhhornn** [comment]
Thanks for contributing @Sparsh47 
You can as well spread the gospel of this repo

**Comment by Sparsh47** [comment]
So have my pr been approved?

**Comment by jhhornn** [comment]
Yes it has @Sparsh47

**Review by jhhornn — COMMENTED** [review]
Thanks for contributing

**Pull request merged**
